app = "arqui-bot"

[build]
  # se usares Dockerfile, basta deixar assim
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[processes]
  app = "python main.py"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
